# -*- coding: utf-8 -*-
"""Adult.Gui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fU5D9x6LsbNX_KMXIv7zZPnw3sGcTZqW
"""

import gradio as gr
import pandas as pd
import joblib

model = joblib.load("adult_income_model.pkl")
def predict_income(
    age,
    workclass,
    fnlwgt,
    education,
    educational_num,
    marital_status,
    occupation,
    relationship,
    race,
    gender,
    capital_gain,
    capital_loss,
    hours_per_week,
    native_country
):
    data = pd.DataFrame([{
        "age": age,
        "workclass": workclass,
        "fnlwgt": fnlwgt,
        "education": education,
        "educational-num": educational_num,
        "marital-status": marital_status,
        "occupation": occupation,
        "relationship": relationship,
        "race": race,
        "gender": gender,
        "capital-gain": capital_gain,
        "capital-loss": capital_loss,
        "hours-per-week": hours_per_week,
        "native-country": native_country
    }])


    data["age_group"] = pd.cut(
        data["age"],
        bins=[0, 25, 35, 50, 100],
        labels=["Young", "Adult", "Middle_Age", "Senior"]
    )

    data["capital_net"] = (
        data["capital-gain"] - data["capital-loss"]
    )

    data["hours_group"] = pd.cut(
        data["hours-per-week"],
        bins=[0, 30, 40, 60, 100],
        labels=["Low", "Normal", "High", "Very_High"]
    )


    prediction = model.predict(data)[0]
    return prediction


demo = gr.Interface(
    fn=predict_income,

    inputs=[
        gr.Number(label="Age", value=30),
        gr.Textbox(label="Workclass", value="Private"),
        gr.Number(label="fnlwgt", value=100000),
        gr.Textbox(label="Education", value="Bachelors"),
        gr.Number(label="Educational Number", value=13),
        gr.Textbox(label="Marital Status", value="Married-civ-spouse"),
        gr.Textbox(label="Occupation", value="Exec-managerial"),
        gr.Textbox(label="Relationship", value="Husband"),
        gr.Textbox(label="Race", value="White"),
        gr.Textbox(label="Gender", value="Male"),
        gr.Number(label="Capital Gain", value=0),
        gr.Number(label="Capital Loss", value=0),
        gr.Number(label="Hours per Week", value=40),
        gr.Textbox(label="Native Country", value="United-States")
    ],

    outputs=gr.Textbox(label="Predicted Income"),
    title="Adult Income Prediction",
    description="Enter a person's information to predict whether their income is <=50K or >50K."
)

demo.launch()